# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - 27018:27017
    volumes:
      - './mongodb:/data/db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

#docker-compose -f mongo-composer.yml up
#docker-compose -f mongo-composer.yml up --detach

