// <auto-generated />
using System;
using Extension.Infracstructure;
using Extension.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Extension.Infracstructure.Migrations
{
    [DbContext(typeof(ExtensionDbContext))]
    [Migration("20231101100613_update-db-17h05-11012023")]
    partial class updatedb17h0511012023
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Extension.Domain.Entities.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("AppConfig");
                });

            modelBuilder.Entity("Extension.Domain.Entities.ClientCard", b =>
                {
                    b.Property<Guid>("ClientCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("ClientCardId");

                    b.ToTable("ClientCards");
                });

            modelBuilder.Entity("Extension.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("CurencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("longtext");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CurencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Extension.Domain.Entities.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Availability")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientCardId")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ClientCardId1")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductImageSrc")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductTitle")
                        .HasColumnType("longtext");

                    b.Property<int>("SourcePageId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("ProductId");

                    b.HasIndex("ClientCardId1");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("SourcePageId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Extension.Domain.Entities.SourcePage", b =>
                {
                    b.Property<int>("SourcePageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext");

                    b.Property<string>("PageName")
                        .HasColumnType("longtext");

                    b.HasKey("SourcePageId");

                    b.ToTable("SourcePages");
                });

            modelBuilder.Entity("Extension.Domain.Entities.Products", b =>
                {
                    b.HasOne("Extension.Domain.Entities.ClientCard", "ClientCard")
                        .WithMany("Products")
                        .HasForeignKey("ClientCardId1");

                    b.HasOne("Extension.Domain.Entities.Currency", "Currency")
                        .WithMany("Products")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Extension.Domain.Entities.SourcePage", "SourcePage")
                        .WithMany("Products")
                        .HasForeignKey("SourcePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCard");

                    b.Navigation("Currency");

                    b.Navigation("SourcePage");
                });

            modelBuilder.Entity("Extension.Domain.Entities.ClientCard", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Extension.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Extension.Domain.Entities.SourcePage", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
